export const electronicsCategories = [
  "PHONE",
  "TABLET",
  "HEADPHONES",
  "HEATER",
  "SPEAKER",
  "HAIR_CLIPPER",
  "COOLER",
  "POWER_BANK",
  "KETTLE",
  "LAPTOP",
  "MULTI_SOCKET",
  "PIZZA_PAN_CABLE",
  "PAN",
  "GLASSES",
  "AUX",
  "WATCH",
  "ADAPTOR",
  "HANDSFREE",
  "CABLE",
  "HAIR_CUTTER",
  "HAIR_DRYER",
  "FAN",
  "PRINTER",
  "ELECTRONIC_CIGARETTE",
  "STOVE",
  "PIZZA_PAN",
  "WIRELESS",
  "EAR_PAD",
  "SMART_WATCH",
  "XBOX360",
  "TOASTER",
  "TAILOR_MACHINE",
  "BATTERY",
  "PHONE_CASE",
  "BRACELET",
  "TESBIH",
  "HAND_MIXER",
  "COMPUTER",
  "SEWING_MACHINE",
  "WATER_HEATER",
  "PUMP",
  "KEYBOARD",
  "PLUG",
  "WATER_BOILER",
  "THERAPY",
  "COFFEE_MAKER",
  "KITCHEN",
  "BOARD",
  "MAT",
  "RADIO",
  "VACUUM_CLEANER",
  "OTHER",
] as const;

export type ElectronicsCategoryValue = (typeof electronicsCategories)[number];

export const electronicsCategoryLabels: Record<ElectronicsCategoryValue, string> = {
  PHONE: "Phone",
  TABLET: "Tablet",
  HEADPHONES: "Headphones",
  HEATER: "Heater",
  SPEAKER: "Speaker",
  HAIR_CLIPPER: "Hair Clipper",
  COOLER: "Cooler",
  POWER_BANK: "Power Bank",
  KETTLE: "Kettle",
  LAPTOP: "Laptop",
  MULTI_SOCKET: "Multi Socket",
  PIZZA_PAN_CABLE: "Pizza Pan Cable",
  PAN: "Pan",
  GLASSES: "Glasses",
  AUX: "Aux",
  WATCH: "Watch",
  ADAPTOR: "Adaptor",
  HANDSFREE: "Handsfree",
  CABLE: "Cable",
  HAIR_CUTTER: "Hair Cutter",
  HAIR_DRYER: "Hair Dryer",
  FAN: "Fan",
  PRINTER: "Printer",
  ELECTRONIC_CIGARETTE: "Electronic Cigarette",
  STOVE: "Stove",
  PIZZA_PAN: "Pizza Pan",
  WIRELESS: "Wireless",
  EAR_PAD: "Ear Pad",
  SMART_WATCH: "Smart Watch",
  XBOX360: "Xbox 360",
  TOASTER: "Toaster",
  TAILOR_MACHINE: "Tailor Machine",
  BATTERY: "Battery",
  PHONE_CASE: "Phone Case",
  BRACELET: "Bracelet",
  TESBIH: "Tesbih",
  HAND_MIXER: "Hand Mixer",
  COMPUTER: "Computer",
  SEWING_MACHINE: "Sewing Machine",
  WATER_HEATER: "Water Heater",
  PUMP: "Pump",
  KEYBOARD: "Keyboard",
  PLUG: "Plug",
  WATER_BOILER: "Water Boiler",
  THERAPY: "Therapy",
  COFFEE_MAKER: "Coffee Maker",
  KITCHEN: "Kitchen",
  BOARD: "Board",
  MAT: "Mat",
  RADIO: "Radio",
  VACUUM_CLEANER: "Vacuum Cleaner",
  OTHER: "Other",
};

const electronicsCategoryImages: Record<ElectronicsCategoryValue, string> = {
  PHONE: "/images/electronics/phone.svg",
  TABLET: "/images/electronics/tablet.svg",
  HEADPHONES: "/images/electronics/audio.svg",
  HEATER: "/images/electronics/heat.svg",
  SPEAKER: "/images/electronics/audio.svg",
  HAIR_CLIPPER: "/images/electronics/grooming.svg",
  COOLER: "/images/electronics/fan.svg",
  POWER_BANK: "/images/electronics/battery.svg",
  KETTLE: "/images/electronics/kitchen.svg",
  LAPTOP: "/images/electronics/computer.svg",
  MULTI_SOCKET: "/images/electronics/cable.svg",
  PIZZA_PAN_CABLE: "/images/electronics/cable.svg",
  PAN: "/images/electronics/kitchen.svg",
  GLASSES: "/images/electronics/other.svg",
  AUX: "/images/electronics/cable.svg",
  WATCH: "/images/electronics/watch.svg",
  ADAPTOR: "/images/electronics/cable.svg",
  HANDSFREE: "/images/electronics/audio.svg",
  CABLE: "/images/electronics/cable.svg",
  HAIR_CUTTER: "/images/electronics/grooming.svg",
  HAIR_DRYER: "/images/electronics/grooming.svg",
  FAN: "/images/electronics/fan.svg",
  PRINTER: "/images/electronics/printer.svg",
  ELECTRONIC_CIGARETTE: "/images/electronics/other.svg",
  STOVE: "/images/electronics/kitchen.svg",
  PIZZA_PAN: "/images/electronics/kitchen.svg",
  WIRELESS: "/images/electronics/audio.svg",
  EAR_PAD: "/images/electronics/audio.svg",
  SMART_WATCH: "/images/electronics/watch.svg",
  XBOX360: "/images/electronics/gaming.svg",
  TOASTER: "/images/electronics/kitchen.svg",
  TAILOR_MACHINE: "/images/electronics/machine.svg",
  BATTERY: "/images/electronics/battery.svg",
  PHONE_CASE: "/images/electronics/phone.svg",
  BRACELET: "/images/electronics/watch.svg",
  TESBIH: "/images/electronics/other.svg",
  HAND_MIXER: "/images/electronics/kitchen.svg",
  COMPUTER: "/images/electronics/computer.svg",
  SEWING_MACHINE: "/images/electronics/machine.svg",
  WATER_HEATER: "/images/electronics/heat.svg",
  PUMP: "/images/electronics/machine.svg",
  KEYBOARD: "/images/electronics/computer.svg",
  PLUG: "/images/electronics/cable.svg",
  WATER_BOILER: "/images/electronics/kitchen.svg",
  THERAPY: "/images/electronics/other.svg",
  COFFEE_MAKER: "/images/electronics/kitchen.svg",
  KITCHEN: "/images/electronics/kitchen.svg",
  BOARD: "/images/electronics/other.svg",
  MAT: "/images/electronics/other.svg",
  RADIO: "/images/electronics/audio.svg",
  VACUUM_CLEANER: "/images/electronics/cleaning.svg",
  OTHER: "/images/electronics/other.svg",
};

export function getElectronicsCategoryImage(
  category: ElectronicsCategoryValue | string
) {
  return electronicsCategoryImages[
    category as ElectronicsCategoryValue
  ] ?? "/images/electronics/other.svg";
}
